# Generated by Django 2.2.11 on 2020-04-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200407_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_name',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
