# Generated by Django 2.2.11 on 2020-04-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_vote_vote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_name',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False),
        ),
    ]
